ln -sf $(pwd)/kget /usr/local/bin/kget
ln -sf $(pwd)/execpod /usr/local/bin/execpod
ln -sf $(pwd)/tailpod /usr/local/bin/tailpod
ln -sf $(pwd)/kdesc /usr/local/bin/kdesc
ln -sf $(pwd)/krestart /usr/local/bin/krestart
ln -sf $(pwd)/kstern /usr/local/bin/kstern
ln -sf $(pwd)/pfpod /usr/local/bin/pfpod
ln -sf $(pwd)/kedit /usr/local/bin/kedit
ln -sf $(pwd)/kdelete /usr/local/bin/kdelete
ln -sf $(pwd)/kube-fzf.sh  /usr/local/bin/kube-fzf.sh
