ln -sf $(pwd)/findpod /usr/local/bin/findpod
ln -sf $(pwd)/execpod /usr/local/bin/execpod
ln -sf $(pwd)/tailpod /usr/local/bin/tailpod
ln -sf $(pwd)/desc /usr/local/bin/desc
ln -sf $(pwd)/restart /usr/local/bin/restart
ln -sf $(pwd)/pfpod /usr/local/bin/pfpod
ln -sf $(pwd)/edit /usr/local/bin/edit
ln -sf $(pwd)/tssh /usr/local/bin/tssh
ln -sf $(pwd)/kube-fzf.sh  /usr/local/bin/kube-fzf.sh
