ln -sf $(pwd)/findpod /usr/local/bin/findpod
ln -sf $(pwd)/execpod /usr/local/bin/execpod
ln -sf $(pwd)/tailpod /usr/local/bin/tailpod
ln -sf $(pwd)/describepod /usr/local/bin/descepod
ln -sf $(pwd)/descnode /usr/local/bin/descnode
ln -sf $(pwd)/pfpod /usr/local/bin/pfpod
ln -sf $(pwd)/editvs /usr/local/bin/editvs
ln -sf $(pwd)/editsvc /usr/local/bin/editsvc
ln -sf $(pwd)/editcj /usr/local/bin/editcj
ln -sf $(pwd)/editdeploy /usr/local/bin/editdeploy
ln -sf $(pwd)/editdr /usr/local/bin/editdr
ln -sf $(pwd)/tssh /usr/local/bin/tssh
ln -sf $(pwd)/kube-fzf/kube-fzf.sh  /usr/local/bin/kube-fzf.sh
