#!/usr/bin/env bash

set -e
set -o pipefail

[[ -z "${KUBE_FZF_PATH}" ]] && source kube-fzf.sh || source $KUBE_FZF_PATH
rollout() {
  local namespace_query pod_query result namespace rs_name
  local rs=$1
  if [[ $rs == *"-"* ]]; then
      _kube_fzf_usage "krestart"
      return 1
  elif [ -z "$rs" ]; then
      _kube_fzf_usage "krestart"
      return 1
  fi
  _kube_fzf_handler "restart" "$2"  "$3" "$4" "$5" "$6"
  namespace_query=$(echo $args | awk -F '|' '{ print $1 }')
  pod_query=$(echo $args | awk -F '|' '{ print $2 }')
  context_selector=$(echo $args | awk -F '|' '{ print $5 }')
  
  result=$(_kube_fzf_search "$namespace_query" "$pod_query" "$context_selector" "$rs") 
  IFS=$'|' read -r namespace rs_name <<< "$result"

  _kube_fzf_echo "kubectl rollout restart $rs $rs_name --namespace='$namespace' --context '$context_selector'"
  read -p "kubectl rollout restart $rs $rs_name --namespace='$namespace' --context '$context_selector' Are you Sure? " -n 1 -r
  echo 
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    kubectl rollout restart $rs $rs_name --namespace=$namespace --context $context_selector
  fi
}

rollout "$@"
