#!/usr/bin/env bash

set -e
set -o pipefail

[[ -z "${KUBE_FZF_PATH}" ]] && source kube-fzf.sh || source $KUBE_FZF_PATH
tssh() {
  tsh login
  result=$(tsh ls | fzf | awk '{ print $1 }') 

  tsh ssh root@$result
}

tssh "$@"
